# Generated by Django 3.2.8 on 2021-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamming_gerald_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='song_artist',
            field=models.CharField(default='no artist', max_length=200),
        ),
    ]
