# Generated by Django 3.2.8 on 2021-10-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamming_gerald_app', '0002_music_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='song_date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
